server:
  port: 8082

swagger:
  description: Student Portal Rest API

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/schooldb?serverTimezone=UTC
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    #    show-sql: true
    properties:
      hibernate:
        formart_sql: true